import type { Recognition } from "../src/shared/protocol";

export interface CatalogEntry {
  recognition: Recognition;
  aliases: string[];
  visibleWords: string[];
  provenance: { curated: string; era: "classic" | "recent"; representation: string };
}
// Every reference has local media, replaced in place when the catalog changes.
// Sources credit the original media; third-party images are not original Codememes artwork.
const memes: [
  id: string,
  name: string,
  aliases: string[],
  era: "classic" | "recent",
  kind: "image" | "gif",
  asset: string,
  poster: string | null,
  width: number,
  height: number,
  description: string,
  visible: string,
  source: string,
][] = [
  [
    "this-is-fine",
    "This is fine",
    ["fine"],
    "classic",
    "image",
    "this-is-fine.webp",
    null,
    580,
    282,
    "A dog sits calmly in a room engulfed in fire.",
    "This is fine",
    "https://imgflip.com/memegenerator/55311130",
  ],
  [
    "one-does-not",
    "One does not simply",
    ["boromir"],
    "classic",
    "image",
    "one-does-not.webp",
    null,
    568,
    335,
    "Boromir raises his hand while explaining something.",
    "",
    "https://imgflip.com/memegenerator/61579",
  ],
  [
    "much-wow",
    "Such wow. Much amaze.",
    ["doge", "much wow"],
    "classic",
    "image",
    "much-wow.webp",
    null,
    600,
    600,
    "Kabosu the Shiba Inu looks sideways at the camera.",
    "",
    "https://api.memegen.link/images/doge.jpg",
  ],
  [
    "distracted-boyfriend",
    "Distracted boyfriend",
    ["distracted boyfriend"],
    "classic",
    "image",
    "distracted-boyfriend.webp",
    null,
    600,
    400,
    "A man looks back at a passing woman while his girlfriend reacts.",
    "",
    "https://imgflip.com/memegenerator/112126428",
  ],
  [
    "change-my-mind",
    "Change my mind",
    ["change my mind"],
    "classic",
    "image",
    "change-my-mind.webp",
    null,
    482,
    361,
    "A man sits behind a campus table with a Change my mind sign.",
    "Change my mind",
    "https://imgflip.com/memegenerator/129242436",
  ],
  [
    "surprised-pikachu",
    "Surprised Pikachu",
    ["shocked pikachu"],
    "classic",
    "image",
    "surprised-pikachu.webp",
    null,
    600,
    600,
    "Pikachu stares with wide eyes and an open mouth.",
    "",
    "https://imgflip.com/memegenerator/155067746",
  ],
  [
    "expanding-brain",
    "Expanding brain",
    ["galaxy brain"],
    "classic",
    "image",
    "expanding-brain.webp",
    null,
    428,
    600,
    "Four increasingly glowing brains form a vertical sequence.",
    "",
    "https://imgflip.com/memegenerator/93895088",
  ],
  [
    "woman-yelling-cat",
    "Woman yelling at a cat",
    ["smudge"],
    "classic",
    "image",
    "woman-yelling-cat.webp",
    null,
    600,
    386,
    "A woman points angrily beside a confused white cat at a dinner table.",
    "",
    "https://imgflip.com/memegenerator/188390779",
  ],
  [
    "distracted-math",
    "Confused math lady",
    ["math lady", "confused lady"],
    "classic",
    "gif",
    "distracted-math.gif",
    null,
    280,
    179,
    "A confused woman considers floating mathematical equations.",
    "",
    "https://media1.tenor.com/m/CowGNQSUsOYAAAAC/confused-math.gif",
  ],
  [
    "hide-the-pain",
    "Hide the pain Harold",
    ["harold"],
    "classic",
    "image",
    "hide-the-pain.webp",
    null,
    479,
    600,
    "Harold holds a mug and smiles with visibly strained eyes.",
    "",
    "https://imgflip.com/memegenerator/27813981",
  ],
  [
    "success-kid",
    "Success kid",
    ["success baby"],
    "classic",
    "image",
    "success-kid.webp",
    null,
    600,
    579,
    "A toddler clenches a fist with a determined expression.",
    "",
    "https://api.memegen.link/images/success.jpg",
  ],
  [
    "drake-hotline",
    "Drake approves",
    ["drake", "hotline bling"],
    "classic",
    "image",
    "drake-hotline.webp",
    null,
    600,
    600,
    "Drake rejects one option and smiles approvingly at another.",
    "",
    "https://imgflip.com/memegenerator/181913649",
  ],
  [
    "rickroll",
    "Never gonna give you up",
    ["rickroll", "rickrolling"],
    "classic",
    "gif",
    "rickroll.gif",
    null,
    280,
    280,
    "Rick Astley sings and dances beside a microphone.",
    "",
    "https://media1.tenor.com/m/x8v1oNUOmg4AAAAC/rickroll-roll.gif",
  ],
  [
    "all-your-base",
    "All your base are belong to us",
    ["all your base"],
    "classic",
    "image",
    "all-your-base.webp",
    null,
    600,
    452,
    "The Zero Wing villain speaks through a translated game dialogue box.",
    "All your base are belong to us",
    "https://api.memegen.link/images/zero-wing.jpg",
  ],
  [
    "ceiling-cat",
    "Ceiling cat is watching you",
    ["ceiling cat"],
    "classic",
    "gif",
    "ceiling-cat.gif",
    null,
    280,
    189,
    "A cat peeks down from above.",
    "",
    "https://media1.tenor.com/m/Wrk5ISBrPJ0AAAAC/peek-cat.gif",
  ],
  [
    "nyan-cat",
    "Nyan cat",
    ["nyan"],
    "classic",
    "gif",
    "nyan-cat.gif",
    null,
    240,
    152,
    "A pixel cat with a pastry body flies through space trailing a rainbow.",
    "",
    "https://media1.tenor.com/m/zBc1XhcbTSoAAAAC/nyan-cat-rainbow.gif",
  ],
  [
    "keyboard-cat",
    "Play him off, keyboard cat",
    ["keyboard cat"],
    "classic",
    "gif",
    "keyboard-cat.gif",
    null,
    280,
    210,
    "An orange cat in a blue shirt plays an electronic keyboard.",
    "",
    "https://media1.tenor.com/m/ivB_FxyjV1cAAAAC/keyboard-cat-keycat.gif",
  ],
  [
    "is-this-pigeon",
    "Is this a pigeon?",
    ["pigeon"],
    "classic",
    "image",
    "is-this-pigeon.webp",
    null,
    600,
    539,
    "An anime character gestures toward a butterfly.",
    "",
    "https://imgflip.com/memegenerator/100777631",
  ],
  [
    "two-buttons",
    "Two buttons, one sweaty choice",
    ["two buttons"],
    "classic",
    "image",
    "two-buttons.webp",
    null,
    396,
    600,
    "A sweating man faces two red buttons.",
    "",
    "https://imgflip.com/memegenerator/87743020",
  ],
  [
    "stonks",
    "Stonks",
    ["stonk"],
    "classic",
    "image",
    "stonks.webp",
    null,
    600,
    422,
    "A suited mannequin stands in front of a rising stock chart.",
    "Stonks",
    "https://api.memegen.link/images/stonks.jpg",
  ],
  [
    "always-has-been",
    "Always has been",
    ["wait it's all"],
    "classic",
    "image",
    "always-has-been.webp",
    null,
    600,
    338,
    "Two astronauts look toward Earth as one realizes something.",
    "",
    "https://imgflip.com/memegenerator/252600902",
  ],
  [
    "they-same",
    "They're the same picture",
    ["same picture"],
    "classic",
    "image",
    "they-same.webp",
    null,
    537,
    600,
    "Pam from The Office compares two pictures and says they are the same.",
    "They're the same picture",
    "https://imgflip.com/memegenerator/180190441",
  ],
  [
    "we-have-home",
    "We have that at home",
    ["at home"],
    "classic",
    "image",
    "we-have-home.webp",
    null,
    600,
    600,
    "A disappointed child considers the food waiting at home.",
    "",
    "https://api.memegen.link/images/home.jpg",
  ],
  [
    "uno-reverse",
    "UNO reverse card",
    ["reverse card"],
    "classic",
    "gif",
    "uno-reverse.gif",
    null,
    183,
    280,
    "A reverse card spins into view.",
    "",
    "https://media1.tenor.com/m/8XNZFtwJxscAAAAC/reverse-card-uno.gif",
  ],
  [
    "let-him-cook",
    "Let him cook",
    ["cooking"],
    "recent",
    "gif",
    "let-him-cook.gif",
    null,
    280,
    215,
    "Woody gestures to let someone continue cooking.",
    "Let him cook",
    "https://media1.tenor.com/m/xZQGJoezqe4AAAAC/let-him-cook-woody.gif",
  ],
  [
    "girl-dinner",
    "Girl dinner",
    ["girl dinner"],
    "recent",
    "gif",
    "girl-dinner.gif",
    null,
    216,
    280,
    "Pasta pours onto a plate under a Girl dinner caption.",
    "Girl dinner",
    "https://media1.tenor.com/m/4d6-_D4YaesAAAAC/girldinner-girl-dinner.gif",
  ],
  [
    "very-demure",
    "Very demure, very mindful",
    ["demure", "mindful"],
    "recent",
    "gif",
    "very-demure.gif",
    null,
    232,
    280,
    "A speaker demonstrates a composed look with a demure caption.",
    "Very demure very mindful",
    "https://media1.tenor.com/m/z4rrqqQVyI8AAAAC/demure-mindful.gif",
  ],
  [
    "side-eye",
    "Bombastic side eye",
    ["side eye"],
    "recent",
    "gif",
    "side-eye.gif",
    null,
    280,
    209,
    "A dog gives the camera a suspicious sideways glance.",
    "",
    "https://media1.tenor.com/m/0Ci6Qnq9HOYAAAAC/side-eye-dog-suspicious.gif",
  ],
  [
    "fries-bag",
    "Just put the fries in the bag",
    ["fries in the bag"],
    "recent",
    "gif",
    "fries-bag.gif",
    null,
    280,
    247,
    "A person holds a fast-food bag in a captioned reaction clip.",
    "Just put the fries in the bag",
    "https://media1.tenor.com/m/RPoE6ruIb1kAAAAC/trump-just-put-the-fries-in-the-bag.gif",
  ],
  [
    "aura-farming",
    "Aura farming",
    ["aura"],
    "recent",
    "gif",
    "aura-farming.gif",
    null,
    280,
    279,
    "The Pacu Jalur boat dancer moves confidently at the bow of a racing boat.",
    "",
    "https://media1.tenor.com/m/wb_rblUTxVAAAAAC/boat-kid-aura-farming-pacu-jalur.gif",
  ],
  [
    "six-seven",
    "Six seven",
    ["67", "sixseven"],
    "recent",
    "gif",
    "six-seven.gif",
    null,
    280,
    180,
    "The six-seven kid grins and makes the palms-up gesture.",
    "67",
    "https://media1.tenor.com/m/tJO6kM3FePUAAAAC/67-67-kid.gif",
  ],
  [
    "delulu",
    "Delulu is the solulu",
    ["delulu", "solulu"],
    "recent",
    "gif",
    "delulu.gif",
    null,
    280,
    158,
    "A captioned reaction celebrates being delulu.",
    "Delulu is the solulu",
    "https://media1.tenor.com/m/ApTYj2YayxoAAAAC/adoringfavss-elpri.gif",
  ],
  [
    "main-character",
    "Main character energy",
    ["main character"],
    "recent",
    "gif",
    "main-character.gif",
    null,
    280,
    280,
    "Maurice reacts with a main-character-energy caption.",
    "That's main character energy",
    "https://media1.tenor.com/m/77FWQGiGpsgAAAAC/that%27s-main-character-energy-maurice.gif",
  ],
  [
    "disaster-girl",
    "Disaster Girl",
    [],
    "classic",
    "image",
    "disaster-girl.webp",
    null,
    500,
    375,
    "A young girl smiles at the camera as a house burns behind her.",
    "",
    "https://imgflip.com/memegenerator/97984",
  ],
  [
    "waiting-skeleton",
    "Waiting skeleton",
    ["waiting"],
    "classic",
    "image",
    "waiting-skeleton.webp",
    null,
    298,
    403,
    "A skeleton waits on a bench.",
    "",
    "https://imgflip.com/memegenerator/4087833",
  ],
  [
    "sad-pablo",
    "Sad Pablo Escobar",
    ["pablo", "narcos"],
    "classic",
    "image",
    "sad-pablo.webp",
    null,
    600,
    591,
    "Pablo Escobar waits alone in three quiet scenes.",
    "",
    "https://imgflip.com/memegenerator/80707627",
  ],
  [
    "trade-offer",
    "Trade offer",
    ["trade"],
    "recent",
    "image",
    "trade-offer.webp",
    null,
    459,
    600,
    "A suited man holds his fingers together beneath a Trade offer heading.",
    "",
    "https://imgflip.com/memegenerator/309868304",
  ],
  [
    "once-again-asking",
    "I am once again asking",
    ["bernie"],
    "classic",
    "image",
    "once-again-asking.webp",
    null,
    600,
    600,
    "Bernie Sanders stands outdoors in a winter coat.",
    "",
    "https://imgflip.com/memegenerator/222403160",
  ],
  [
    "exit-ramp",
    "Left exit 12",
    ["exit ramp"],
    "classic",
    "image",
    "exit-ramp.webp",
    null,
    600,
    572,
    "A car swerves toward a highway exit.",
    "",
    "https://imgflip.com/memegenerator/124822590",
  ],
  [
    "anakin-padme",
    "Anakin and Padme",
    ["for the better"],
    "classic",
    "image",
    "anakin-padme.webp",
    null,
    600,
    600,
    "Anakin and Padme talk in four panels as her expression turns concerned.",
    "",
    "https://imgflip.com/memegenerator/322841258",
  ],
  [
    "epic-handshake",
    "Epic handshake",
    ["predator handshake"],
    "classic",
    "image",
    "epic-handshake.webp",
    null,
    600,
    430,
    "Two muscular arms clasp hands.",
    "",
    "https://imgflip.com/memegenerator/135256802",
  ],
  [
    "grus-plan",
    "Gru's plan",
    ["gru"],
    "classic",
    "image",
    "grus-plan.webp",
    null,
    600,
    385,
    "Gru presents a plan, then looks back at his own board.",
    "",
    "https://imgflip.com/memegenerator/131940431",
  ],
  [
    "running-balloon",
    "Running away balloon",
    ["balloon"],
    "classic",
    "image",
    "running-balloon.webp",
    null,
    446,
    600,
    "A person reaches for a balloon while another holds them back.",
    "",
    "https://imgflip.com/memegenerator/131087935",
  ],
  [
    "batman-robin",
    "Batman slapping Robin",
    ["batman slap"],
    "classic",
    "image",
    "batman-robin.webp",
    null,
    400,
    387,
    "Batman slaps Robin in a comic panel.",
    "",
    "https://imgflip.com/memegenerator/438680",
  ],
  [
    "everywhere",
    "Everywhere",
    ["buzz", "woody"],
    "classic",
    "image",
    "everywhere.webp",
    null,
    600,
    408,
    "Buzz Lightyear gestures around the room beside Woody.",
    "",
    "https://imgflip.com/memegenerator/91538330",
  ],
  [
    "bike-fall",
    "Bike fall",
    ["stick in spokes"],
    "classic",
    "image",
    "bike-fall.webp",
    null,
    441,
    600,
    "A cyclist puts a stick in his own spokes and falls.",
    "",
    "https://imgflip.com/memegenerator/79132341",
  ],
  [
    "ancient-aliens",
    "Ancient aliens",
    ["aliens"],
    "classic",
    "image",
    "ancient-aliens.webp",
    null,
    500,
    436,
    "Giorgio Tsoukalos gestures with his hands and distinctive hair.",
    "",
    "https://imgflip.com/memegenerator/101470",
  ],
  [
    "mocking-spongebob",
    "Mocking SpongeBob",
    ["mocking"],
    "classic",
    "image",
    "mocking-spongebob.webp",
    null,
    502,
    353,
    "SpongeBob crouches and makes a mocking face.",
    "",
    "https://imgflip.com/memegenerator/102156234",
  ],
  [
    "getting-paid",
    "You guys are getting paid?",
    ["getting paid"],
    "classic",
    "image",
    "getting-paid.webp",
    null,
    520,
    358,
    "A confused young man raises his eyebrows at his companions.",
    "",
    "https://imgflip.com/memegenerator/177682295",
  ],
  [
    "buff-doge-cheems",
    "Buff Doge vs. Cheems",
    ["cheems"],
    "classic",
    "image",
    "buff-doge-cheems.webp",
    null,
    600,
    461,
    "A muscular Doge stands beside a small worried Cheems.",
    "",
    "https://imgflip.com/memegenerator/247375501",
  ],
  [
    "absolute-cinema",
    "Absolute cinema",
    ["cinema", "scorsese"],
    "recent",
    "image",
    "absolute-cinema.webp",
    null,
    600,
    465,
    "Martin Scorsese raises both hands in a black-and-white portrait.",
    "",
    "https://imgflip.com/memegenerator/505705955",
  ],
  [
    "squidward-window",
    "Squidward at the window",
    ["squidward"],
    "classic",
    "image",
    "squidward-window.webp",
    null,
    598,
    420,
    "Squidward looks out at SpongeBob and Patrick having fun.",
    "",
    "https://imgflip.com/memegenerator/67452763",
  ],
  [
    "oprah-giveaway",
    "You get a car",
    ["oprah"],
    "classic",
    "image",
    "oprah-giveaway.webp",
    null,
    600,
    449,
    "Oprah points excitedly during a giveaway.",
    "",
    "https://imgflip.com/memegenerator/28251713",
  ],
  [
    "tuxedo-pooh",
    "Tuxedo Winnie the Pooh",
    ["fancy pooh"],
    "classic",
    "image",
    "tuxedo-pooh.webp",
    null,
    600,
    437,
    "Ordinary Winnie the Pooh is paired with a smug tuxedo version.",
    "",
    "https://imgflip.com/memegenerator/178591752",
  ],
  [
    "monkey-puppet",
    "Monkey puppet side eye",
    ["awkward monkey"],
    "classic",
    "image",
    "monkey-puppet.webp",
    null,
    600,
    499,
    "A monkey puppet glances sideways and then faces forward.",
    "",
    "https://imgflip.com/memegenerator/148909805",
  ],
  [
    "two-guys-bus",
    "Two guys on a bus",
    ["bus"],
    "recent",
    "image",
    "two-guys-bus.webp",
    null,
    600,
    531,
    "Two passengers see opposite views from the same bus.",
    "",
    "https://imgflip.com/memegenerator/354700819",
  ],
  [
    "clown-makeup",
    "Clown applying makeup",
    ["clown"],
    "classic",
    "image",
    "clown-makeup.webp",
    null,
    564,
    600,
    "A person adds clown makeup in four stages.",
    "",
    "https://imgflip.com/memegenerator/195515965",
  ],
  [
    "roll-safe",
    "Roll Safe",
    ["think about it"],
    "classic",
    "image",
    "roll-safe.webp",
    null,
    600,
    338,
    "A man smiles knowingly and taps his temple.",
    "",
    "https://imgflip.com/memegenerator/89370399",
  ],
  [
    "evil-kermit",
    "Evil Kermit",
    ["kermit"],
    "classic",
    "image",
    "evil-kermit.webp",
    null,
    600,
    279,
    "Kermit faces a hooded version of himself.",
    "",
    "https://imgflip.com/memegenerator/84341851",
  ],
  [
    "flex-tape",
    "Flex Tape",
    ["phil swift"],
    "classic",
    "image",
    "flex-tape.webp",
    null,
    510,
    572,
    "Phil Swift slaps a piece of tape over a leaking tank.",
    "",
    "https://imgflip.com/memegenerator/166969924",
  ],
  [
    "three-headed-dragon",
    "Three-headed dragon",
    ["dragon"],
    "classic",
    "image",
    "three-headed-dragon.webp",
    null,
    600,
    480,
    "Two serious dragon heads sit beside one goofy head.",
    "",
    "https://imgflip.com/memegenerator/187102311",
  ],
  [
    "scientist-myself",
    "Something of a scientist myself",
    ["scientist", "norman osborn"],
    "classic",
    "image",
    "scientist-myself.webp",
    null,
    600,
    300,
    "Norman Osborn smiles during a conversation.",
    "",
    "https://imgflip.com/memegenerator/133946291",
  ],
  [
    "laughing-leo",
    "Laughing Leo",
    ["leonardo"],
    "classic",
    "image",
    "laughing-leo.webp",
    null,
    470,
    470,
    "Leonardo DiCaprio laughs while holding a drink.",
    "",
    "https://imgflip.com/memegenerator/259237855",
  ],
  [
    "bad-luck-brian",
    "Bad Luck Brian",
    ["brian"],
    "classic",
    "image",
    "bad-luck-brian.webp",
    null,
    475,
    562,
    "A boy in a sweater vest smiles for his school photo.",
    "",
    "https://imgflip.com/memegenerator/61585",
  ],
  [
    "panik-kalm",
    "Panik Kalm Panik",
    ["panik", "kalm"],
    "classic",
    "image",
    "panik-kalm.webp",
    null,
    436,
    600,
    "A cartoon figure alternates between panic and calm.",
    "",
    "https://imgflip.com/memegenerator/226297822",
  ],
  [
    "do-something",
    "C'mon, do something",
    ["do something"],
    "classic",
    "image",
    "do-something.webp",
    null,
    448,
    519,
    "A simply drawn person pokes an object with a stick.",
    "",
    "https://imgflip.com/memegenerator/20007896",
  ],
  [
    "leo-cheers",
    "Leonardo DiCaprio cheers",
    ["gatsby", "cheers"],
    "classic",
    "image",
    "leo-cheers.webp",
    null,
    600,
    400,
    "Jay Gatsby raises a champagne glass in a toast.",
    "",
    "https://imgflip.com/memegenerator/5496396",
  ],
  [
    "rock-driving",
    "The Rock driving",
    ["the rock"],
    "classic",
    "image",
    "rock-driving.webp",
    null,
    487,
    600,
    "The Rock turns to look at his passenger while driving.",
    "",
    "https://imgflip.com/memegenerator/21735",
  ],
  [
    "charlie-conspiracy",
    "Charlie conspiracy",
    ["pepe silvia"],
    "classic",
    "image",
    "charlie-conspiracy.webp",
    null,
    600,
    450,
    "Charlie gestures at a wall covered in papers and red string.",
    "",
    "https://imgflip.com/memegenerator/92084495",
  ],
  [
    "press-f",
    "Press F to pay respects",
    ["press f"],
    "classic",
    "gif",
    "press-f.gif",
    null,
    498,
    278,
    "The Call of Duty funeral scene prompts the player to press F to pay respects.",
    "Press F to pay respects",
    "https://media1.tenor.com/m/enlgLAA9qnsAAAAC/press-f-pay-respect.gif",
  ],
  [
    "404",
    "404 Not Found",
    ["404", "not found"],
    "classic",
    "gif",
    "404.gif",
    null,
    498,
    498,
    "A sourced animated 404 Not Found error reaction.",
    "404 Not Found",
    "https://media1.tenor.com/m/IHdlTRsmcS4AAAAC/404.gif",
  ],
  [
    "dvd-screensaver",
    "DVD screensaver",
    ["bouncing dvd", "dvd"],
    "classic",
    "gif",
    "dvd-screensaver.gif",
    null,
    498,
    280,
    "The DVD logo bounces around a dark screen.",
    "DVD",
    "https://media1.tenor.com/m/stKjYPvgKDgAAAAC/dvd-old.gif",
  ],
];
function words(value: string): string[] {
  return value.match(/[\p{L}\p{N}]+(?:['’][\p{L}]+)?/gu) ?? [];
}
export const DECK: readonly CatalogEntry[] = memes.map(
  ([id, name, aliases, era, kind, asset, poster, width, height, description, visible, source]) => ({
    recognition: {
      id,
      family: id,
      name,
      description,
      kind,
      phrase: name,
      asset: `/media/${asset}`,
      ...(poster ? { poster: `/media/${poster}` } : {}),
      width,
      height,
      attribution: source,
    },
    aliases,
    visibleWords: words(`${name} ${visible}`),
    provenance: { curated: "2026-10-05", era, representation: source },
  }),
);

// Explicit allowlist also protects against future curator fields being persisted/public.
export function recognitionView(source: Recognition): Recognition {
  return {
    id: source.id,
    family: source.family,
    name: source.name,
    description: source.description,
    kind: source.kind,
    phrase: source.phrase,
    width: source.width,
    height: source.height,
    ...(source.asset ? { asset: source.asset } : {}),
    ...(source.poster ? { poster: source.poster } : {}),
    ...(source.attribution ? { attribution: source.attribution } : {}),
  };
}
export function normalizeRecognition(value: string): string {
  return value.normalize("NFKC").toLocaleLowerCase("en-US").replace(/[’]/g, "'").trim();
}
